name: Release

on:
  push:
    branches:
      - main

jobs:
  release-3:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./gradlew dockerBuildImage
      - run: docker push hankcp/geoip2-docker
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: hankcp/geoip2-docker:2.15.0, hankcp/geoip2-docker:latest
